### Import Libraries

In [1]:
import tensorflow as tf

- **Version Check**

In [2]:
print(tf.__version__)

2.16.2


<!-- -->

### Basics

- #### Two Dimensional Array/Tensor

Note: In Tensorflow n-dimensional array is known and stored as Tensor object like below.

In [3]:
# col1, col2, col3
x = tf.constant([[10., 20., 30.], # row1
                [40., 50., 60]] # row2
                )

print(type(x)) # n-dimensional array stored as internal tensor object
print(x)
print(x.shape)
print(x.dtype)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[10. 20. 30.]
 [40. 50. 60.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


- **Mathematical Operations**

In [4]:
# Adding n-dimensional tensor with same values 
x_add = x + x

print(x_add)
print(x_add.shape)

tf.Tensor(
[[ 20.  40.  60.]
 [ 80. 100. 120.]], shape=(2, 3), dtype=float32)
(2, 3)


In [7]:
# Multiplying n-dimensional tensor with constant value
x_ml_c = x * 5

print(x_ml_c)
print(x_ml_c.shape)

tf.Tensor(
[[ 50. 100. 150.]
 [200. 250. 300.]], shape=(2, 3), dtype=float32)
(2, 3)


In [24]:
# Dot product of n-dimensional tensor with same values i.e., matrix multiplication --> sum(row * column)
x_dot_product = x @ tf.transpose(x)

print(x)
print(tf.transpose(x))
print(x_dot_product, "\n\n")
print("Dot Product / Matrix Multiplication")
print(x_dot_product.shape, "\n\n")

# Explanation of matrix matrix multiplication
print("Explanation of matrix matrix multiplication")
print("x[00]position:", (10.*10.) + (20.*20.) + (30.*30.))
print("x[01]position:", (10.*40.) + (20.*50.) + (30.*60.))
print("x[10]position:", (40.*10.) + (50.*20.) + (60.*30.))
print("x[11]position:", (40.*40.) + (50.*50.) + (60.*60.))

tf.Tensor(
[[10. 20. 30.]
 [40. 50. 60.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[10. 40.]
 [20. 50.]
 [30. 60.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1400. 3200.]
 [3200. 7700.]], shape=(2, 2), dtype=float32) 


Dot Product / Matrix Multiplication
(2, 2) 


Explanation of matrix matrix multiplication
x[00]position: 1400.0
x[01]position: 3200.0
x[10]position: 3200.0
x[11]position: 7700.0


In [28]:
# Data Concat
x_concat = tf.concat([x,x], axis=0) # Row wise addition

print(x)
print(x.shape)
print(x_concat)
print(x_concat.shape)

tf.Tensor(
[[10. 20. 30.]
 [40. 50. 60.]], shape=(2, 3), dtype=float32)
(2, 3)
tf.Tensor(
[[10. 20. 30.]
 [40. 50. 60.]
 [10. 20. 30.]
 [40. 50. 60.]], shape=(4, 3), dtype=float32)
(4, 3)


In [29]:
tf.nn.softmax(x, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2.0610598e-09, 4.5397872e-05, 9.9995458e-01],
       [2.0610598e-09, 4.5397872e-05, 9.9995458e-01]], dtype=float32)>